# Example configuration for Black.

[tool.black]
line-length = 88
target-version = ['py36', 'py37', 'py38']
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
max-line-length = 88
include = '\.pyi?$'

exclude = '''
/(
   \.git
  | \.venv
)/
'''
