# Generated by Django 3.1.4 on 2021-04-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210414_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='tenant',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='user_created',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
