# Generated by Django 3.1.4 on 2021-05-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210511_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='b_area_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
