# Generated by Django 3.1.4 on 2021-05-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tenant_b_area_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=225, null=True),
        ),
    ]
