# Generated by Django 3.1.4 on 2021-05-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210526_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesetting',
            name='blocked_companies',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
