# Generated by Django 3.1.4 on 2021-06-01 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_profilesetting_score'),
        ('core', '0011_profilesetting_blocked_companies'),
    ]

    operations = [
    ]
