# Generated by Django 3.1.4 on 2021-06-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='namespace',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='translation_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
