# Generated by Django 3.1.4 on 2021-06-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210601_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_consent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
