# Generated by Django 3.1.4 on 2021-06-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_is_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='translation_type',
        ),
        migrations.AddField(
            model_name='translation',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
