# Generated by Django 3.1.4 on 2021-06-21 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210610_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=191, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='temp/')),
                ('is_uploaded', models.BooleanField(default=False)),
                ('is_parsed', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_processing',
            },
        ),
    ]
