# Generated by Django 3.1.4 on 2021-07-07 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_dataprocessing'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exclude_from', models.CharField(choices=[('sp_candidates_list', 'sp_candidates_list')], default='sp_candidates_list', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluderequestby', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excludeuser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exclude_user',
            },
        ),
    ]
