# Generated by Django 3.1.4 on 2021-07-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delete_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
