# Generated by Django 3.1.4 on 2021-07-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=225, verbose_name='email'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('tenant_id', 'email')},
        ),
    ]
