# Generated by Django 3.1.4 on 2021-07-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210720_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprocessing',
            name='token',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
