# Generated by Django 3.1.4 on 2021-07-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_user_delete_comment'),
        ('core', '0020_auto_20210716_1833'),
    ]

    operations = [
    ]
