# Generated by Django 3.1.4 on 2021-07-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210719_1546'),
        ('core', '0020_auto_20210720_1454'),
    ]

    operations = [
    ]
