# Generated by Django 3.1.4 on 2021-07-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_dataprocessing_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='language_preference',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='language_preference',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='language_preference',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='language_preference',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='profilesetting',
            name='language_preference',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='language_preference',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='language_preference',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
