# Generated by Django 3.1.4 on 2021-07-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210722_1935'),
        ('core', '0022_merge_20210720_2037'),
    ]

    operations = [
    ]
