# Generated by Django 3.1.4 on 2021-07-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_20210723_1821'),
        ('core', '0022_auto_20210719_1543'),
    ]

    operations = [
    ]
