# Generated by Django 3.1.4 on 2021-08-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_user_indeed_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesetting',
            name='authorized_countries',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilesetting',
            name='company_size',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilesetting',
            name='job_roles_preference',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilesetting',
            name='job_types',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilesetting',
            name='remote_work_policy',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='profilesetting',
            name='location_preference',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
