# Generated by Django 3.1.4 on 2021-08-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_question_subquestion_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='erd',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
