# Generated by Django 3.1.4 on 2021-08-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_jobroles'),
        ('core', '0028_tenant_erd'),
    ]

    operations = [
    ]
