# Generated by Django 3.1.4 on 2021-08-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_merge_20210813_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='display_textbox_options',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('all', 'All'), ('other', 'Other')], max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='textbox_label',
            field=models.CharField(blank=True, help_text='For both display_textbox_options we need to seprate text with | pipe operator', max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
