# Generated by Django 3.1.4 on 2021-08-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210818_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprocessing',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
