# Generated by Django 3.1.4 on 2021-09-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210830_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ca',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
