# Generated by Django 3.1.4 on 2021-09-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_user_is_ca'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='is_canada',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
