# Generated by Django 3.1.4 on 2021-10-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_tenant_is_canada'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jobs_summary_notification',
            field=models.CharField(choices=[('daily', 'daily'), ('weekely', 'weekely')], default='weekely', max_length=191, null=True),
        ),
    ]
