# Generated by Django 3.1.4 on 2021-10-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_user_jobs_summary_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='jobs_summary_notification',
        ),
        migrations.AddField(
            model_name='user',
            name='daily_jobs_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='weekely_jobs_summary',
            field=models.BooleanField(default=False),
        ),
    ]
