job_functions = {
    "en": {
        "Accounting": "Accounting",
        "Airlines/Aviation": "Airlines/Aviation",
        "Alternative Dispute Resolution": "Alternative Dispute Resolution",
        "Alternative Medicine": "Alternative Medicine",
        "Animation": "Animation",
        "Apparel/Fashion": "Apparel/Fashion",
        "Architecture & Planning": "Architecture & Planning",
        "Arts & Crafts": "Arts & Crafts",
        "Automotive": "Automotive",
        "Aviation & Aerospace": "Aviation & Aerospace",
        "Banking": "Banking",
        "Biotechnology": "Biotechnology",
        "Broadcast Media": "Broadcast Media",
        "Building Materials": "Building Materials",
        "Business Supplies & Equipments": "Business Supplies & Equipments",
        "Capital Markets": "Capital Markets",
        "Chemicals": "Chemicals",
        "Civic & Social Organization": "Civic & Social Organization",
        "Civil Engineering": "Civil Engineering",
        "Commercial Real Estate": "Commercial Real Estate",
        "Computer & Network Security": "Computer & Network Security",
        "Computer Games": "Computer Games",
        "Computer Hardware": "Computer Hardware",
        "Computer Networking": "Computer Networking",
        "Computer Software": "Computer Software",
        "Construction": "Construction",
        "Consumer Electronics": "Consumer Electronics",
        "Consumer Goods": "Consumer Goods",
        "Consumer Services": "Consumer Services",
        "Cosmetics": "Cosmetics",
        "Dairy": "Dairy",
        "Design": "Design",
        "E-Learning": "E-Learning",
        "Education Management": "Education Management",
        "Electrical/Electronic Manufacturing": "Electrical/Electronic Manufacturing",
        "Entertainment": "Entertainment",
        "Environmental Services": "Environmental Services",
        "Events Services": "Events Services",
        "Executive Office": "Executive Office",
        "Facilities Services": "Facilities Services",
        "Farming": "Farming",
        "Financial Services": "Financial Services",
        "Fine Art": "Fine Art",
        "Fishery": "Fishery",
        "Food & Beverages": "Food & Beverages",
        "Food Production ": "Food Production ",
        "Fund Raising": "Fund Raising",
        "Furniture": "Furniture",
        "Gambling & Casinos": "Gambling & Casinos",
        "Glass, Ceramics & Concrete": "Glass, Ceramics & Concrete",
        "Government Relations": "Government Relations",
        "Graphic Design": "Graphic Design",
        "Health, Wellness & Fitness": "Health, Wellness & Fitness",
        "Higher Education": "Higher Education",
        "Hospital & Health Care": "Hospital & Health Care",
        "Hospitality": "Hospitality",
        "Human Resources": "Human Resources",
        "Import and Export": "Import and Export",
        "Individual & Family Services": "Individual & Family Services",
        "Industrial Automation": "Industrial Automation",
        "Information Technology & Services": "Information Technology & Services",
        "Insurance": "Insurance",
        "International Affairs": "International Affairs",
        "Internation Trade and Development": "Internation Trade and Development",
        "Internet": "Internet",
        "Investment Banking": "Investment Banking",
        "Judiciary": "Judiciary",
        "Law Enforcement": "Law Enforcement",
        "Law Practice": "Law Practice",
        "Legal Services": "Legal Services",
        "Legislative Office": "Legislative Office",
        "Leisure, Travel & Tourism": "Leisure, Travel & Tourism",
        "Libraries": "Libraries",
        "Logistics & Supply Chain": "Logistics & Supply Chain",
        "Luxury Goods & Jewelry": "Luxury Goods & Jewelry",
        "Machinery": "Machinery",
        "Management Consulting": "Management Consulting",
        "Maritime": "Maritime",
        "Market Research": "Market Research",
        "Marketing and Advertising": "Marketing and Advertising",
        "Mechanical or Industrial Engineering": "Mechanical or Industrial Engineering",
        "Media Production": "Media Production",
        "Medical Devices": "Medical Devices",
        "Medical Practice": "Medical Practice",
        "Mental Health Care": "Mental Health Care",
        "Military": "Military",
        "Mining & Metals": "Mining & Metals",
        "Mobile Games": "Mobile Games",
        "Motion Pictures & Films": "Motion Pictures & Films",
        "Museums and Institutions": "Museums and Institutions",
        "Music": "Music",
        "Nanotechnology": "Nanotechnology",
        "Newspapers": "Newspapers",
        "Non-Profit Organization Management": "Non-Profit Organization Management",
        "Oil & Energy": "Oil & Energy",
        "Online Media": "Online Media",
        "Outsourcing/Offshoring": "Outsourcing/Offshoring",
        "Package/Freight Delivery": "Package/Freight Delivery",
        "Packaging and Containers": "Packaging and Containers",
        "Paper & Forest Products": "Paper & Forest Products",
        "Performing Arts": "Performing Arts",
        "Pharmaceuticals": "Pharmaceuticals",
        "Philanthropy": "Philanthropy",
        "Photography": "Photography",
        "Plastics": "Plastics",
        "Political Organization": "Political Organization",
        "Primary/Secondary Organization": "Primary/Secondary Organization",
        "Printing": "Printing",
        "Professional Training & Coaching": "Professional Training & Coaching",
        "Program Development": "Program Development",
        "Public Policy": "Public Policy",
        "Public Relations and Communications": "Public Relations and Communications",
        "Public Safety": "Public Safety",
        "Publishing": "Publishing",
        "Railroad Manufacture": "Railroad Manufacture",
        "Ranching": "Ranching",
        "Real Estate": "Real Estate",
        "Recreational Facilities and Services": "Recreational Facilities and Services",
        "Religious Institutions": "Religious Institutions",
        "Renewables & Envrionment": "Renewables & Envrionment",
        "Research": "Research",
        "Restaurants": "Restaurants",
        "Retail": "Retail",
        "Security and Investigations": "Security and Investigations",
        "Semiconductors": "Semiconductors",
        "Shipbuilding": "Shipbuilding",
        "Sporting Goods": "Sporting Goods",
        "Sports": "Sports",
        "Staffing and Recruiting": "Staffing and Recruiting",
        "Supermarkets": "Supermarkets",
        "Telecommunications": "Telecommunications",
        "Textiles": "Textiles",
        "Think Tanks": "Think Tanks",
        "Tobacco": "Tobacco",
        "Translation and Localization": "Translation and Localization",
        "Transportation/Trucking/Railroad": "Transportation/Trucking/Railroad",
        "Utilities": "Utilities",
        "Venture Capital & Private Equity": "Venture Capital & Private Equity",
        "Veterinary": "Veterinary",
        "Warehousing": "Warehousing",
        "Wholesale": "Wholesale",
        "Wine and Spirits": "Wine and Spirits",
        "Wireless": "Wireless",
        "Writing and Editing": "Writing and Editing",
        "Other": "Other",
        "Administrative": "Administrative",
        "Arts and Design": "Arts and Design",
        "Business Development": "Business Development",
        "Community & Social Services": "Community & Social Services",
        "Consulting": "Consulting",
        "Education": "Education",
        "Engineering": "Engineering",
        "Entrepreneurship": "Entrepreneurship",
        "Finance": "Finance",
        "Healthcare Services": "Healthcare Services",
        "Information Technology": "Information Technology",
        "Legal": "Legal",
        "Marketing": "Marketing",
        "Media & Communications": "Media & Communications",
        "Military & Protective Services": "Military & Protective Services",
        "Operations": "Operations",
        "Product Management": "Product Management",
        "Program & Product Management": "Program & Product Management",
        "Purchasing": "Purchasing",
        "Quality Assurance": "Quality Assurance",
        "Rersearch": "Rersearch",
        "Sales": "Sales",
        "Support": "Support",
    },
    "esp": {
        "Accounting": "Contabilidad",
        "Airlines/Aviation": "Aerolíneas/Aviación",
        "Alternative Dispute Resolution": "Solución Alternativa de Controversias",
        "Alternative Medicine": "Medicina Alternativa",
        "Animation": "Animación",
        "Apparel/Fashion": "Confección/Moda",
        "Architecture & Planning": "Arquitectura y Urbanismo",
        "Arts & Crafts": "Arte y Artesanía",
        "Automotive": "Automotor",
        "Aviation & Aerospace": "Aviación y Aeroespacial",
        "Banking": "Banca",
        "Biotechnology": "Biotecnología",
        "Broadcast Media": "Medios de Radiodifusión",
        "Building Materials": "Materiales de Construcción",
        "Business Supplies & Equipments": "Suministros y Equipamiento Empresarial",
        "Capital Markets": "Mercados de Capitales",
        "Chemicals": "Productos Químicos",
        "Civic & Social Organization": "Organizaciones Cívicas y Sociales",
        "Civil Engineering": "Ingeniería Civil",
        "Commercial Real Estate": "Bienes Raíces Comerciales",
        "Computer & Network Security": "Seguridad Informática y de Redes",
        "Computer Games": "Juegos de Computadora",
        "Computer Hardware": "Hardware de Computadora",
        "Computer Networking": "Redes de Computadora",
        "Computer Software": "Software de Computadora",
        "Construction": "Construcción",
        "Consumer Electronics": "Productos Electrónicos de Consumo",
        "Consumer Goods": "Bienes de Consumo",
        "Consumer Services": "Servicios al Consumidor",
        "Cosmetics": "Productos Cosméticos",
        "Dairy": "Lácteos",
        "Design": "Diseño",
        "E-Learning": "Formación online",
        "Education Management": "Gestión Educativa",
        "Electrical/Electronic Manufacturing": "Fabricación de Productos Eléctricos/Electrónicos",
        "Entertainment": "Entretenimiento",
        "Environmental Services": "Servicios Ambientales",
        "Events Services": "Servicios para Eventos",
        "Executive Office": "Servicios Administrativos",
        "Facilities Services": "Servicios para Instalaciones",
        "Farming": "Producción Agraria",
        "Financial Services": "Servicios Financieros",
        "Fine Art": "Bellas Artes",
        "Fishery": "Pesquería",
        "Food & Beverages": "Alimentos y Bebidas",
        "Food Production ": "Producción de Alimentos",
        "Fund Raising": "Recaudación de Fondos",
        "Furniture": "Mobiliario",
        "Gambling & Casinos": "Casas de Juegos de Azar y Casinos",
        "Glass, Ceramics & Concrete": "Vidrio, Cerámica y Hormigón",
        "Government Relations": "Relaciones Gubernamentales",
        "Graphic Design": "Diseño Gráfico",
        "Health, Wellness & Fitness": "Salud, Bienestar y Fitness",
        "Higher Education": "Educación Superior",
        "Hospital & Health Care": "Atención Médica y Hospitalaria",
        "Hospitality": "Hotelería",
        "Human Resources": "Recursos Humanos",
        "Import and Export": "Importación y Exportación",
        "Individual & Family Services": "Servicios para Individuos y Familias",
        "Industrial Automation": "Automatización Industrial",
        "Information Technology & Services": "Servicios y Tecnología de la Información",
        "Insurance": "Seguros",
        "International Affairs": "Asuntos Internacionales",
        "Internation Trade and Development": "Desarrollo y Comercio Internacional",
        "Internet": "Internet",
        "Investment Banking": "Banca de Inversión",
        "Judiciary": "Sistema Judicial",
        "Law Enforcement": "Aplicación de la Ley",
        "Law Practice": "Práctica Jurídica",
        "Legal Services": "Servicios Jurídicos",
        "Legislative Office": "Oficina Legislativa",
        "Leisure, Travel & Tourism": "Ocio, Viajes y Turismo",
        "Libraries": "Bibliotecas",
        "Logistics & Supply Chain": "Logística y Cadena de Suministro",
        "Luxury Goods & Jewelry": "Artículos de Lujo y Joyería",
        "Machinery": "Maquinaria",
        "Management Consulting": "Consultoría de Gestión",
        "Maritime": "Marítimo",
        "Market Research": "Investigación de Mercado",
        "Marketing and Advertising": "Marketing y Publicidad",
        "Mechanical or Industrial Engineering": "Ingeniería Mecánica o Industrial",
        "Media Production": "Producción de Medios",
        "Medical Devices": "Dispositivos Médicos",
        "Medical Practice": "Práctica Médica",
        "Mental Health Care": "Cuidado de la Salud Mental",
        "Military": "Militar",
        "Mining & Metals": "Minería y Metales",
        "Mobile Games": "Juegos para Teléfonos Móviles",
        "Motion Pictures & Films": "Cinematografía y Películas",
        "Museums and Institutions": "Museos e Instituciones",
        "Music": "Música",
        "Nanotechnology": "Nanotecnología",
        "Newspapers": "Periódicos",
        "Non-Profit Organization Management": "Gestión de Organizaciones Sin Fines de Lucro",
        "Oil & Energy": "Petróleo y Energía",
        "Online Media": "Medios En Línea",
        "Outsourcing/Offshoring": "Subcontratación/Deslocalización",
        "Package/Freight Delivery": "Entrega de Paquetería/Fletes",
        "Packaging and Containers": "Envases y Contenedores",
        "Paper & Forest Products": "Papel y Productos Forestales",
        "Performing Arts": "Artes Escénicas",
        "Pharmaceuticals": "Productos Farmacéuticos",
        "Philanthropy": "Filantropía",
        "Photography": "Fotografía",
        "Plastics": "Plásticos",
        "Political Organization": "Organización Política",
        "Primary/Secondary Organization": "Organización Primaria/Secundaria",
        "Printing": "Impresión",
        "Professional Training & Coaching": "Formación y Entrenamiento Profesional",
        "Program Development": "Desarrollo de Programas",
        "Public Policy": "Política Pública",
        "Public Relations and Communications": "Relaciones Públicas y Comunicaciones",
        "Public Safety": "Seguridad Pública",
        "Publishing": "Industria Editorial",
        "Railroad Manufacture": "Fabricación de Ferrocarriles",
        "Ranching": "Ganadería",
        "Real Estate": "Bienes Raíces  ",
        "Recreational Facilities and Services": "Servicios e Instalaciones Recreativas",
        "Religious Institutions": "Instituciones Religiosas",
        "Renewables & Envrionment": "Energía Renovable y Medioambiente",
        "Research": "Investigación  ",
        "Restaurants": "Restaurantes",
        "Retail": "Venta Minorista",
        "Security and Investigations": "Seguridad e Investigaciones",
        "Semiconductors": "Semiconductores",
        "Shipbuilding": "Construcción Naval",
        "Sporting Goods": "Artículos Deportivos",
        "Sports": "Deportes",
        "Staffing and Recruiting": "Dotación y Selección de Personal",
        "Supermarkets": "Supermercados",
        "Telecommunications": "Telecomunicaciones",
        "Textiles": "Textiles",
        "Think Tanks": "Grupos de Expertos",
        "Tobacco": "Tabaco",
        "Translation and Localization": "Traducción y Localización",
        "Transportation/Trucking/Railroad": "Transporte/Camiones/Ferrocarriles",
        "Utilities": "Servicios Públicos",
        "Venture Capital & Private Equity": "Capital de Riesgo y Capital Privado",
        "Veterinary": "Veterinaria",
        "Warehousing": "Almacenamiento",
        "Wholesale": "Venta al por Mayor",
        "Wine and Spirits": "Vino y Bebidas Espirituosas",
        "Wireless": "Sector Inalámbrico",
        "Writing and Editing": "Escritura y Edición",
        "Other": "Otra",
        "Administrative": "Administrativa",
        "Arts and Design": "Arte y Diseño",
        "Business Development": "Desarrollo de negocios",
        "Community & Social Services": "Servicios sociales y comunitarios",
        "Consulting": "Consultante",
        "Education": "Educación",
        "Engineering": "Ingeniería",
        "Entrepreneurship": "Emprendimiento",
        "Finance": "Finanzas",
        "Healthcare Services": "Servicios de atención médica",
        "Information Technology": "Tecnologías de la información",
        "Legal": "Legal",
        "Marketing": "Márketing",
        "Media & Communications": "Medios y Comunicaciones",
        "Military & Protective Services": "Servicios militares y de protección",
        "Operations": "Operaciones",
        "Product Management": "Gestión de productos",
        "Program & Product Management": "Gestión de programas y productos",
        "Purchasing": "Adquisitiva",
        "Quality Assurance": "Seguro de calidad",
        "Rersearch": "Investigar",
        "Sales": "Ventas",
        "Support": "Apoyo",
    },
    "fr": {
        "Accounting": "Comptabilité",
        "Airlines/Aviation": "Compagnies aériennes et aviation",
        "Alternative Dispute Resolution": "Règlement extrajudiciaire des litiges",
        "Alternative Medicine": "Médecine alternative",
        "Animation": "Animation",
        "Apparel/Fashion": "Mode et vêtements",
        "Architecture & Planning": "Architecture et planification",
        "Arts & Crafts": "Art et artisanat",
        "Automotive": "Automobile",
        "Aviation & Aerospace": "Aviation et aérospatial",
        "Banking": "Banque",
        "Biotechnology": "Biotechnologie",
        "Broadcast Media": "Médias radiotélévisés",
        "Building Materials": "Matériaux de construction",
        "Business Supplies & Equipments": "Fournitures et équipements d’entreprise",
        "Capital Markets": "Marchés des capitaux",
        "Chemicals": "Produits chimiques",
        "Civic & Social Organization": "Organisation civique et sociale",
        "Civil Engineering": "Génie civil",
        "Commercial Real Estate": "Immobilier commercial",
        "Computer & Network Security": "Sécurité des ordinateurs et des réseaux",
        "Computer Games": "Jeux vidéo",
        "Computer Hardware": "Matériel informatique",
        "Computer Networking": "Réseau informatique",
        "Computer Software": "Logiciels d’ordinateur",
        "Construction": "Construction",
        "Consumer Electronics": "Appareils électroniques grand public",
        "Consumer Goods": "Biens de consommation",
        "Consumer Services": "Services aux consommateurs",
        "Cosmetics": "Cosmétiques",
        "Dairy": "Produits laitiers",
        "Design": "Design",
        "E-Learning": "Apprentissage électronique",
        "Education Management": "Gestion de l’éducation",
        "Electrical/Electronic Manufacturing": "Fabrication électrique et électronique",
        "Entertainment": "Divertissement",
        "Environmental Services": "Services environnementaux",
        "Events Services": "Services d’événements",
        "Executive Office": "Présidence-direction générale",
        "Facilities Services": "Services d’installations",
        "Farming": "Agriculture",
        "Financial Services": "Services financiers",
        "Fine Art": "Beaux-arts",
        "Fishery": "Pêche",
        "Food & Beverages": "Alimentation et boissons",
        "Food Production ": "Production alimentaire",
        "Fund Raising": "Collecte de fonds",
        "Furniture": "Mobilier",
        "Gambling & Casinos": "Jeux de hasard et casinos",
        "Glass, Ceramics & Concrete": "Verre, céramique et béton",
        "Government Relations": "Relations gouvernementales",
        "Graphic Design": "Design graphique",
        "Health, Wellness & Fitness": "Santé, bien-être et forme physique",
        "Higher Education": "Enseignement supérieur",
        "Hospital & Health Care": "Hôpitaux et soins de santé",
        "Hospitality": "Tourisme d’accueil",
        "Human Resources": "Ressources humaines",
        "Import and Export": "Importation et exportation",
        "Individual & Family Services": "Services aux particuliers et aux familles",
        "Industrial Automation": "Automatisation industrielle",
        "Information Technology & Services": "Technologies et services de l’information",
        "Insurance": "Assurances",
        "International Affairs": "Affaires internationales",
        "Internation Trade and Development": "Commerce international et développement",
        "Internet": "Internet",
        "Investment Banking": "Banque d’investissement",
        "Judiciary": "Système judiciaire",
        "Law Enforcement": "Application de la loi",
        "Law Practice": "Pratique du droit",
        "Legal Services": "Services juridiques",
        "Legislative Office": "Bureau législatif",
        "Leisure, Travel & Tourism": "Loisirs, voyages et tourisme",
        "Libraries": "Bibliothèques",
        "Logistics & Supply Chain": "Logistique et chaîne d’approvisionnement",
        "Luxury Goods & Jewelry": "Produits de luxe et bijoux",
        "Machinery": "Machinerie",
        "Management Consulting": "Services de conseil en gestion",
        "Maritime": "Services maritimes",
        "Market Research": "Études de marché",
        "Marketing and Advertising": "Marketing et publicité",
        "Mechanical or Industrial Engineering": "Génie mécanique ou industriel",
        "Media Production": "Production de médias",
        "Medical Devices": "Dispositifs médicaux",
        "Medical Practice": "Pratique médicale",
        "Mental Health Care": "Soins de santé mentale",
        "Military": "Services militaires",
        "Mining & Metals": "Mines et métaux",
        "Mobile Games": "Jeux mobiles",
        "Motion Pictures & Films": "Cinéma et films",
        "Museums and Institutions": "Musées et institutions",
        "Music": "Musique",
        "Nanotechnology": "Nanotechnologie",
        "Newspapers": "Journaux",
        "Non-Profit Organization Management": "Gestion des organisations à but non lucratif",
        "Oil & Energy": "Pétrole et énergie",
        "Online Media": "Médias en ligne",
        "Outsourcing/Offshoring": "Externalisation et délocalisation à l’étranger",
        "Pachage/Freight Delivery": "Livraison de colis ou de marchandises",
        "Packaging and Containers": "Emballage et conteneurs",
        "Paper & Forest Products": "Papier et produits forestiers",
        "Performing Arts": "Arts du spectacle",
        "Pharmaceuticals": "Produits pharmaceutiques",
        "Philanthropy": "Philanthropie",
        "Photography": "Photographie",
        "Plastics": "Plastiques",
        "Political Organization": "Organisation politique",
        "Primary/Secondary Organization": "Enseignement primaire et secondaire",
        "Printing": "Impression",
        "Professional Training & Coaching": "Formation professionnelle et encadrement",
        "Program Development": "Développement de programmes",
        "Public Policy": "Politique publique",
        "Public Relations and Communications": "Relations publiques et communications",
        "Public Safety": "Sécurité publique",
        "Publishing": "Édition",
        "Railroad Manufacture": "Fabrication de matériel ferroviaire",
        "Ranching": "Élevage de bétail",
        "Real Estate": "Immobilier",
        "Recreational Facilities and Services": "Installations et services récréatifs",
        "Religious Institutions": "Institutions religieuses",
        "Renewables & Envrionment": "Sources d’énergie renouvelables et environnement",
        "Research": "Recherche",
        "Restaurants": "Restauration",
        "Retail": "Commerce de détail",
        "Security and Investigations": "Sécurité et enquêtes",
        "Semiconductors": "Semi-conducteurs",
        "Shipbuilding": "Construction navale",
        "Sporting Goods": "Articles de sport",
        "Sports": "Sports",
        "Staffing and Recruiting": "Dotation en personnel et recrutement",
        "Supermarkets": "Supermarchés",
        "Telecommunications": "Télécommunications",
        "Textiles": "Textiles",
        "Think Tanks": "Groupes de réflexion",
        "Tobacco": "Tabac",
        "Translation and Localization": "Traduction et localisation",
        "Transportation/Trucking/Railroad": "Transport, camionnage et chemins de fer",
        "Utilities": "Services publics",
        "Venture Capital & Private Equity": "Capital-risque et capital-investissement",
        "Veterinary": "Médecine vétérinaire",
        "Warehousing": "Entreposage",
        "Wholesale": "Commerce de gros",
        "Wine and Spirits": "Vins et spiritueux",
        "Wireless": "Sans fil",
        "Writing and Editing": "Rédaction et édition",
        "Administrative": "Administratif",
        "Arts and Design": "Arts et design",
        "Business Development": "Développement des affaires",
        "Community & Social Services": "Services communautaires et sociaux",
        "Consulting": "Services de conseil",
        "Education": "Éducation",
        "Engineering": "Ingénierie",
        "Entrepreneurship": "Entrepreneuriat",
        "Finance": "La finance",
        "Healthcare Services": "Services de santé",
        "Information Technology": "Informatique",
        "Legal": "Légal",
        "Marketing": "Commercialisation",
        "Media & Communications": "Médias et communication",
        "Military & Protective Services": "Services militaires et de protection",
        "Operations": "Opérations",
        "Product Management": "Gestion des produits",
        "Program & Product Management": "Gestion des programmes et des produits",
        "Program Management": "Gestion de programmes",
        "Purchasing": "Achat",
        "Quality Assurance": "Assurance qualité",
        "Sales": "Ventes",
        "Support": "Soutien",
        "Project Management": "Gestion de projets",
        "Other": "Autre",
    },
}
