# Generated by Django 3.1.4 on 2021-04-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_jobalert_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='sov_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
