# Generated by Django 3.1.4 on 2021-06-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jobapplication_sov_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='suggested_score',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='weighted_score',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='userjobmatch',
            name='suggested_score',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
