# Generated by Django 3.1.4 on 2021-07-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210618_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='adzuna_jb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='careerbuilder_jb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='careerjet_jb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='dice_jb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='facebook_jb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='flex_jb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='getwork_jb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='glassdoor_jb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='google_jb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='indeed_jb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='jooble_jb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='monster_jb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='neuvoo_jb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='nexxt_jb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='simplifyhired_jb',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='snaga_jb',
            field=models.BooleanField(default=False),
        ),
    ]
