# Generated by Django 3.1.4 on 2021-07-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20210618_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_board',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
