# Generated by Django 3.1.4 on 2021-07-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20210630_1309'),
        ('job', '0005_job_job_board'),
    ]

    operations = [
    ]
