# Generated by Django 3.1.4 on 2021-07-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_merge_20210712_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
