# Generated by Django 3.1.4 on 2021-07-20 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20210719_1621'),
        ('job', '0006_merge_20210712_1149'),
    ]

    operations = [
    ]
