# Generated by Django 3.1.4 on 2021-07-22 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_merge_20210720_1056'),
        ('job', '0007_jobbookmark_is_archived'),
    ]

    operations = [
    ]
