# Generated by Django 3.1.4 on 2021-07-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_merge_20210720_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_board',
        ),
        migrations.AddField(
            model_name='category',
            name='language_preference',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='industry',
            name='language_preference',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='jobcompany',
            name='language_preference',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='jobqualification',
            name='language_preference',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='language_preference',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='language_preference',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
