# Generated by Django 3.1.4 on 2021-07-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_merge_20210722_1555'),
        ('job', '0008_auto_20210722_1935'),
    ]

    operations = [
    ]
