# Generated by Django 3.1.4 on 2021-07-26 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_merge_20210726_1146'),
        ('job', '0007_merge_20210720_1105'),
        ('job', '0007_jobapplication_resume_id'),
    ]

    operations = [
    ]
