# Generated by Django 3.1.4 on 2021-08-03 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0011_auto_20210728_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='users',
            field=models.ManyToManyField(help_text='Users (ep admin and ep members) assign to this job', related_name='jobusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
