# Generated by Django 3.1.4 on 2021-08-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_auto_20210804_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='scheduled_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
