# Generated by Django 3.1.4 on 2021-08-06 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0014_jobapplication_scheduled_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Users (ep admin and ep members) assign to this job', related_name='jobusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
