# Generated by Django 3.1.4 on 2021-08-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0015_auto_20210806_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjobmatch',
            name='discover',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
