# Generated by Django 3.1.4 on 2021-08-10 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0026_user_indeed_id'),
        ('job', '0015_auto_20210806_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_tenant', models.CharField(blank=True, max_length=191, null=True)),
                ('type', models.CharField(choices=[('post-interview', 'PostInterview'), ('job-closed', 'JobClosed')], default='post-interview', max_length=191)),
                ('answers', models.JSONField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('datestamp', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='job.jobapplication')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='job.job')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='_survey', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'job_surveys',
                'db_table': 'job_survey',
            },
        ),
    ]
