# Generated by Django 3.1.4 on 2021-08-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_userjobmatch_discover'),
        ('job', '0018_auto_20210813_1649'),
    ]

    operations = [
    ]
