# Generated by Django 3.1.4 on 2021-08-26 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_merge_20210813_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategoryWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=191, null=True)),
                ('weight', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'job_category_weight',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='score_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='job.jobcategoryweight'),
        ),
    ]
