# Generated by Django 3.1.4 on 2021-08-30 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_auto_20210826_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='score_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='job.jobcategoryweight'),
        ),
    ]
