# Generated by Django 3.1.4 on 2021-09-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_auto_20210830_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description_esp',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='description_fr',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobskill',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
