# Generated by Django 3.1.4 on 2021-09-02 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_auto_20210901_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title_esp',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='title_fr',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
