export const countryList = [
    { countryCode: "US", value: "+1", content: "USA (+1)" },
    { countryCode: "GB", value: "+44", content: "UK (+44)" },
    { countryCode: "DZ", value: "+213", content: "Algeria (+213)" },
    { countryCode: "AD", value: "+376", content: "Andorra (+376)" },
    { countryCode: "AO", value: "+244", content: "Angola (+244)" },
    { countryCode: "AI", value: "+1264", content: "Anguilla (+1264)" },
    { countryCode: "AG", value: "+268", content: "Antigua (+268)" },
    { countryCode: "AG", value: "+268", content: "Barbuda (+268)" },
    { countryCode: "AR", value: "+54", content: "Argentina (+54)" },
    { countryCode: "AM", value: "+374", content: "Armenia (+374)" },
    { countryCode: "AW", value: "+297", content: "Aruba (+297)" },
    { countryCode: "AU", value: "+61", content: "Australia (+61)" },
    { countryCode: "AT", value: "+43", content: "Austria (+43)" },
    { countryCode: "AZ", value: "+994", content: "Azerbaijan (+994)" },
    { countryCode: "BS", value: "+1242", content: "Bahamas (+1242)" },
    { countryCode: "BH", value: "+973", content: "Bahrain (+973)" },
    { countryCode: "BD", value: "+880", content: "Bangladesh (+880)" },
    { countryCode: "BB", value: "+1246", content: "Barbados (+1246)" },
    { countryCode: "BY", value: "+375", content: "Belarus (+375)" },
    { countryCode: "BE", value: "+32", content: "Belgium (+32)" },
    { countryCode: "BZ", value: "+501", content: "Belize (+501)" },
    { countryCode: "BJ", value: "+229", content: "Benin (+229)" },
    { countryCode: "BM", value: "+1441", content: "Bermuda (+1441)" },
    { countryCode: "BT", value: "+975", content: "Bhutan (+975)" },
    { countryCode: "BO", value: "+591", content: "Bolivia (+591)" },
    { countryCode: "BA", value: "+387", content: "Bosnia Herzegovina (+387)" },
    { countryCode: "BW", value: "+267", content: "Botswana (+267)" },
    { countryCode: "BR", value: "+55", content: "Brazil (+55)" },
    { countryCode: "BN", value: "+673", content: "Brunei (+673)" },
    { countryCode: "BG", value: "+359", content: "Bulgaria (+359)" },
    { countryCode: "BF", value: "+226", content: "Burkina Faso (+226)" },
    { countryCode: "BI", value: "+257", content: "Burundi (+257)" },
    { countryCode: "KH", value: "+855", content: "Cambodia (+855)" },
    { countryCode: "CM", value: "+237", content: "Cameroon (+237)" },
    { countryCode: "CA", value: "+1", content: "Canada (+1)" },
    { countryCode: "CV", value: "+238", content: "Cape Verde Islands (+238)" },
    { countryCode: "KY", value: "+1345", content: "Cayman Islands (+1345)" },
    { countryCode: "CF", value: "+236", content: "Central African Republic (+236)" },
    { countryCode: "CL", value: "+56", content: "Chile (+56)" },
    { countryCode: "CN", value: "+86", content: "China (+86)" },
    { countryCode: "CO", value: "+57", content: "Colombia (+57)" },
    { countryCode: "KM", value: "+269", content: "Comoros (+269)" },
    { countryCode: "CG", value: "+242", content: "Congo (+242)" },
    { countryCode: "CK", value: "+682", content: "Cook Islands (+682)" },
    { countryCode: "CR", value: "+506", content: "Costa Rica (+506)" },
    { countryCode: "HR", value: "+385", content: "Croatia (+385)" },
    { countryCode: "CU", value: "+53", content: "Cuba (+53)" },
    { countryCode: "CY", value: "+90", content: "Cyprus - North (+90)" },
    { countryCode: "CY", value: "+357", content: "Cyprus - South (+357)" },
    { countryCode: "CZ", value: "+420", content: "Czech Republic (+420)" },
    { countryCode: "DK", value: "+45", content: "Denmark (+45)" },
    { countryCode: "DJ", value: "+253", content: "Djibouti (+253)" },
    { countryCode: "DM", value: "+1809", content: "Dominica (+1809)" },
    { countryCode: "DO", value: "+1809", content: "Dominican Republic (+1809)" },
    { countryCode: "EC", value: "+593", content: "Ecuador (+593)" },
    { countryCode: "EG", value: "+20", content: "Egypt (+20)" },
    { countryCode: "SV", value: "+503", content: "El Salvador (+503)" },
    { countryCode: "GQ", value: "+240", content: "Equatorial Guinea (+240)" },
    { countryCode: "ER", value: "+291", content: "Eritrea (+291)" },
    { countryCode: "EE", value: "+372", content: "Estonia (+372)" },
    { countryCode: "ET", value: "+251", content: "Ethiopia (+251)" },
    { countryCode: "FK", value: "+500", content: "Falkland Islands (+500)" },
    { countryCode: "FO", value: "+298", content: "Faroe Islands (+298)" },
    { countryCode: "FJ", value: "+679", content: "Fiji (+679)" },
    { countryCode: "FI", value: "+358", content: "Finland (+358)" },
    { countryCode: "FR", value: "+33", content: "France (+33)" },
    { countryCode: "GF", value: "+594", content: "French Guiana (+594)" },
    { countryCode: "PF", value: "+689", content: "French Polynesia (+689)" },
    { countryCode: "GA", value: "+241", content: "Gabon (+241)" },
    { countryCode: "GM", value: "+220", content: "Gambia (+220)" },
    { countryCode: "GE", value: "+7880", content: "Georgia (+7880)" },
    { countryCode: "DE", value: "+49", content: "Germany (+49)" },
    { countryCode: "GH", value: "+233", content: "Ghana (+233)" },
    { countryCode: "GI", value: "+350", content: "Gibraltar (+350)" },
    { countryCode: "GR", value: "+30", content: "Greece (+30)" },
    { countryCode: "GL", value: "+299", content: "Greenland (+299)" },
    { countryCode: "GD", value: "+1473", content: "Grenada (+1473)" },
    { countryCode: "GP", value: "+590", content: "Guadeloupe (+590)" },
    { countryCode: "GU", value: "+671", content: "Guam (+671)" },
    { countryCode: "GT", value: "+502", content: "Guatemala (+502)" },
    { countryCode: "GN", value: "+224", content: "Guinea (+224)" },
    { countryCode: "GW", value: "+245", content: "Guinea - Bissau (+245)" },
    { countryCode: "GY", value: "+592", content: "Guyana (+592)" },
    { countryCode: "HT", value: "+509", content: "Haiti (+509)" },
    { countryCode: "HN", value: "+504", content: "Honduras (+504)" },
    { countryCode: "HK", value: "+852", content: "Hong Kong (+852)" },
    { countryCode: "HU", value: "+36", content: "Hungary (+36)" },
    { countryCode: "IS", value: "+354", content: "Iceland (+354)" },
    { countryCode: "IN", value: "+91", content: "India (+91)" },
    { countryCode: "ID", value: "+62", content: "Indonesia (+62)" },
    { countryCode: "IQ", value: "+964", content: "Iraq (+964)" },
    { countryCode: "IR", value: "+98", content: "Iran (+98)" },
    { countryCode: "IE", value: "+353", content: "Ireland (+353)" },
    { countryCode: "IL", value: "+972", content: "Israel (+972)" },
    { countryCode: "IT", value: "+39", content: "Italy (+39)" },
    { countryCode: "JM", value: "+1876", content: "Jamaica (+1876)" },
    { countryCode: "JP", value: "+81", content: "Japan (+81)" },
    { countryCode: "JO", value: "+962", content: "Jordan (+962)" },
    { countryCode: "KZ", value: "+7", content: "Kazakhstan (+7)" },
    { countryCode: "KE", value: "+254", content: "Kenya (+254)" },
    { countryCode: "KI", value: "+686", content: "Kiribati (+686)" },
    { countryCode: "KP", value: "+850", content: "Korea - North (+850)" },
    { countryCode: "KR", value: "+82", content: "Korea - South (+82)" },
    { countryCode: "KW", value: "+965", content: "Kuwait (+965)" },
    { countryCode: "KG", value: "+996", content: "Kyrgyzstan (+996)" },
    { countryCode: "LA", value: "+856", content: "Laos (+856)" },
    { countryCode: "LV", value: "+371", content: "Latvia (+371)" },
    { countryCode: "LB", value: "+961", content: "Lebanon (+961)" },
    { countryCode: "LS", value: "+266", content: "Lesotho (+266)" },
    { countryCode: "LR", value: "+231", content: "Liberia (+231)" },
    { countryCode: "LY", value: "+218", content: "Libya (+218)" },
    { countryCode: "LI", value: "+417", content: "Liechtenstein (+417)" },
    { countryCode: "LT", value: "+370", content: "Lithuania (+370)" },
    { countryCode: "LU", value: "+352", content: "Luxembourg (+352)" },
    { countryCode: "MO", value: "+853", content: "Macao (+853)" },
    { countryCode: "MK", value: "+389", content: "Macedonia (+389)" },
    { countryCode: "MG", value: "+261", content: "Madagascar (+261)" },
    { countryCode: "MW", value: "+265", content: "Malawi (+265)" },
    { countryCode: "MY", value: "+60", content: "Malaysia (+60)" },
    { countryCode: "MV", value: "+960", content: "Maldives (+960)" },
    { countryCode: "ML", value: "+223", content: "Mali (+223)" },
    { countryCode: "MT", value: "+356", content: "Malta (+356)" },
    { countryCode: "MH", value: "+692", content: "Marshall Islands (+692)" },
    { countryCode: "MQ", value: "+596", content: "Martinique (+596)" },
    { countryCode: "MR", value: "+222", content: "Mauritania (+222)" },
    { countryCode: "YT", value: "+269", content: "Mayotte (+269)" },
    { countryCode: "MX", value: "+52", content: "Mexico (+52)" },
    { countryCode: "FM", value: "+691", content: "Micronesia (+691)" },
    { countryCode: "MD", value: "+373", content: "Moldova (+373)" },
    { countryCode: "MC", value: "+377", content: "Monaco (+377)" },
    { countryCode: "MN", value: "+976", content: "Mongolia (+976)" },
    { countryCode: "MS", value: "+1664", content: "Montserrat (+1664)" },
    { countryCode: "MA", value: "+212", content: "Morocco (+212)" },
    { countryCode: "MZ", value: "+258", content: "Mozambique (+258)" },
    { countryCode: "MN", value: "+95", content: "Myanmar (+95)" },
    { countryCode: "NA", value: "+264", content: "Namibia (+264)" },
    { countryCode: "NR", value: "+674", content: "Nauru (+674)" },
    { countryCode: "NP", value: "+977", content: "Nepal (+977)" },
    { countryCode: "NL", value: "+31", content: "Netherlands (+31)" },
    { countryCode: "NC", value: "+687", content: "New Caledonia (+687)" },
    { countryCode: "NZ", value: "+64", content: "New Zealand (+64)" },
    { countryCode: "NI", value: "+505", content: "Nicaragua (+505)" },
    { countryCode: "NE", value: "+227", content: "Niger (+227)" },
    { countryCode: "NG", value: "+234", content: "Nigeria (+234)" },
    { countryCode: "NU", value: "+683", content: "Niue (+683)" },
    { countryCode: "NF", value: "+672", content: "Norfolk Islands (+672)" },
    { countryCode: "NP", value: "+670", content: "Northern Marianas (+670)" },
    { countryCode: "NO", value: "+47", content: "Norway (+47)" },
    { countryCode: "OM", value: "+968", content: "Oman (+968)" },
    { countryCode: "PK", value: "+92", content: "Pakistan (+92)" },
    { countryCode: "PW", value: "+680", content: "Palau (+680)" },
    { countryCode: "PA", value: "+507", content: "Panama (+507)" },
    { countryCode: "PG", value: "+675", content: "Papua New Guinea (+675)" },
    { countryCode: "PY", value: "+595", content: "Paraguay (+595)" },
    { countryCode: "PE", value: "+51", content: "Peru (+51)" },
    { countryCode: "PH", value: "+63", content: "Philippines (+63)" },
    { countryCode: "PL", value: "+48", content: "Poland (+48)" },
    { countryCode: "PT", value: "+351", content: "Portugal (+351)" },
    { countryCode: "PR", value: "+1787", content: "Puerto Rico (+1787)" },
    { countryCode: "QA", value: "+974", content: "Qatar (+974)" },
    { countryCode: "RE", value: "+262", content: "Reunion (+262)" },
    { countryCode: "RO", value: "+40", content: "Romania (+40)" },
    { countryCode: "RU", value: "+7", content: "Russia (+7)" },
    { countryCode: "RW", value: "+250", content: "Rwanda (+250)" },
    { countryCode: "SM", value: "+378", content: "San Marino (+378)" },
    { countryCode: "ST", value: "+239", content: "Sao Tome & Principe (+239)" },
    { countryCode: "SA", value: "+966", content: "Saudi Arabia (+966)" },
    { countryCode: "SN", value: "+221", content: "Senegal (+221)" },
    { countryCode: "CS", value: "+381", content: "Serbia (+381)" },
    { countryCode: "SC", value: "+248", content: "Seychelles (+248)" },
    { countryCode: "SL", value: "+232", content: "Sierra Leone (+232)" },
    { countryCode: "SG", value: "+65", content: "Singapore (+65)" },
    { countryCode: "SK", value: "+421", content: "Slovak Republic (+421)" },
    { countryCode: "SI", value: "+386", content: "Slovenia (+386)" },
    { countryCode: "SB", value: "+677", content: "Solomon Islands (+677)" },
    { countryCode: "SO", value: "+252", content: "Somalia (+252)" },
    { countryCode: "ZA", value: "+27", content: "South Africa (+27)" },
    { countryCode: "ES", value: "+34", content: "Spain (+34)" },
    { countryCode: "LK", value: "+94", content: "Sri Lanka (+94)" },
    { countryCode: "SH", value: "+290", content: "St. Helena (+290)" },
    { countryCode: "KN", value: "+1869", content: "St. Kitts (+1869)" },
    { countryCode: "SC", value: "+1758", content: "St. Lucia (+1758)" },
    { countryCode: "SR", value: "+597", content: "Suriname (+597)" },
    { countryCode: "SD", value: "+249", content: "Sudan (+249)" },
    { countryCode: "SZ", value: "+268", content: "Swaziland (+268)" },
    { countryCode: "SE", value: "+46", content: "Sweden (+46)" },
    { countryCode: "CH", value: "+41", content: "Switzerland (+41)" },
    { countryCode: "TW", value: "+886", content: "Taiwan (+886)" },
    { countryCode: "TJ", value: "+992", content: "Tajikistan (+992)" },
    { countryCode: "TH", value: "+66", content: "Thailand (+66)" },
    { countryCode: "TG", value: "+228", content: "Togo (+228)" },
    { countryCode: "TO", value: "+676", content: "Tonga (+676)" },
    { countryCode: "TT", value: "+1868", content: "Trinidad & Tobago (+1868)" },
    { countryCode: "TN", value: "+216", content: "Tunisia (+216)" },
    { countryCode: "TR", value: "+90", content: "Turkey (+90)" },
    { countryCode: "TM", value: "+993", content: "Turkmenistan (+993)" },
    { countryCode: "TC", value: "+1649", content: "Turks & Caicos Islands (+1649)" },
    { countryCode: "TV", value: "+688", content: "Tuvalu (+688)" },
    { countryCode: "UG", value: "+256", content: "Uganda (+256)" },
    { countryCode: "UA", value: "+380", content: "Ukraine (+380)" },
    { countryCode: "AE", value: "+971", content: "United Arab Emirates (+971)" },
    { countryCode: "UY", value: "+598", content: "Uruguay (+598)" },
    { countryCode: "UZ", value: "+998", content: "Uzbekistan (+998)" },
    { countryCode: "VU", value: "+678", content: "Vanuatu (+678)" },
    { countryCode: "VA", value: "+379", content: "Vatican City (+379)" },
    { countryCode: "VE", value: "+58", content: "Venezuela (+58)" },
    { countryCode: "VN", value: "+84", content: "Vietnam (+84)" },
    { countryCode: "VG", value: "+1", content: "Virgin Islands - British (+1)" },
    { countryCode: "VI", value: "+1", content: "Virgin Islands - US (+1)" },
    { countryCode: "WF", value: "+681", content: "Wallis & Futuna (+681)" },
    { countryCode: "YE", value: "+969", content: "Yemen (North)(+969)" },
    { countryCode: "YE", value: "+967", content: "Yemen (South)(+967)" },
    { countryCode: "ZM", value: "+260", content: "Zambia (+260)" },
    { countryCode: "ZW", value: "+263", content: "Zimbabwe (+263)" },
];
